[package]
name = "euphonium"
version = "0.0.1"
authors = ["letheka"]
edition = "2018"

[dependencies]
easer = "0.2.1"
failure = "0.1.5"
failure_derive = "0.1.5"
ghakuf = "0.5.3"
hound = "3.4.0"
rand = "0.6"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
